### ISSUE TITLE
Retry on tracker announce failure

### ISSUE THREAD

**Issue by funkybrows** [funkybrows/Deluge-Control#4]

**Comment by funkybrows** [comment]
# Tracker announces repeatedly fail from being executed too early

The irc channel announces a torrent, which is approved by sonarr, and makes its way to deluge before the torrent is actually ready for download.

## What should we do?
In most cases, if you just wait a couple minutes and retry, the torrent should start downloading.

- [ ] Add a class to keep track of Retries

```
class TorrentRetry:
  torrent_id: str
  count: int = 0
  last_check: datetime = now
```
- [ ] Update uploading torrents
```
for each
  if not in client_info:
    setstate(deleted)
  elif state != downloading:
    setstate(state)
    del client_info[torrent_id]
```
- [ ] Add a check_downloading_torrents(db_downloading_torrents, client_torrents)
```

reannounces = []
for torrent in db_torrents:
  if client_torrents[torrent].progress == 0 and total_seeds > 0:
    retry, created = get_or_create_retry
    if not created:
      if retry_count is 0:
        torrent.next_check is now + 2min
        reannounces.append(torrent_id)
      else:
        torrent.next_check += 10min
        reannounces.append(torrent_id)
    else:
      torrent.next_check is now + 30s
  else:
    next_check is now + 30s
  if reannounces:
     core.force_reannounce(torrent_ids: List[str])
```
- [ ] Update check_torrents to collect info for downloading torrents
```
with session:
  query Torrents with downloading state and next check <= utcnow
 ```
 - get client info
 ````
            deluge_client.get_torrents_status(
                ["total_seeds", "state", "progress],
                id=[torrent.torrent_id for torrent in downloading_torrents],
            )
  ```
- commit session 


-
